//////////////////////////////////////////////////////////////////////
// $Source: $
// $Author: dscheibl $
// $Version: 0.0 $
// $Revision: 1.30 $
// $Date: 2005/08/08 13:15:00 $
// Short Description: 
//////////////////////////////////////////////////////////////////////
#ifndef __SP_DLG_SAVECONTINUOUSEQUATIONPROPERTIES__
#define __SP_DLG_SAVECONTINUOUSEQUATIONPROPERTIES__

#include <wx/wx.h>
class SP_ExportContPed2LaTeX;

class SP_DLG_SaveContinuousEquationProperties: public wxDialog
{
private:
  DECLARE_EVENT_TABLE()
  //! the top level sizer
  wxBoxSizer* m_pcSizer;
  wxStaticText* m_pcError;
  SP_ExportContPed2LaTeX* m_pcAnimation;

  DECLARE_CLASS(SP_DLG_SaveContinuousEquationProperties)
protected:
public:
  SP_DLG_SaveContinuousEquationProperties(SP_ExportContPed2LaTeX* p_pcAnim,
    wxWindow* p_pcParent,
    const wxString& p_sTitle = wxT("Save Continuous Equations"),
    long p_nStyle = wxDEFAULT_DIALOG_STYLE);

  /* EVENTS */
  /** \brief  The OnDlgOk function
      \param  p_cEvent	the event object as generated by wx'
      This method is called, if the user clicks the 'OK' button
   */
  void OnDlgOk(wxCommandEvent& p_cEvent);
  /** \brief	The OnDlgCancel function
      \param	p_cEvent	the event object as generated by wx'
      This method is called, if the user clicks the 'Cancel' button, pushes ESC
      or closes the dialog with the window-close methods of the ui-manager.
   */
  void OnDlgCancel(wxCommandEvent& p_cEvent);
};

#endif // __SP_DLG_SAVECONTINUOUSEQUATIONPROPERTIES__

