//////////////////////////////////////////////////////////////////////
// $Source: $
// $Author: mf $
// $Version: 0.0 $
// $Revision: 1.30 $
// $Date: 2003/09/12 11:55:00 $
// Short Description: 
//////////////////////////////////////////////////////////////////////
#ifndef __SP_DLG_GRAPHPROPERTIES_H__
#define __SP_DLG_GRAPHPROPERTIES_H__

#include <wx/wx.h>
#include <wx/gbsizer.h>

#include "sp_ds/SP_DS_Graph.h"

class SP_GUI_Mainframe;

class SP_DLG_GraphProperties: public wxDialog
{
private:
    DECLARE_EVENT_TABLE()
    //! the top level sizer
    wxGridBagSizer* m_pcSizer;
    SP_DS_Graph* m_pcGraph;
    map<wxCheckBox*, SP_DS_Attribute*> m_mAttributes;
    unsigned int m_nCountAttr;
    DECLARE_CLASS(SP_DLG_GraphProperties)
protected:
    bool ShowGraphAttributes();
    wxCheckBox* AddFlagLine(wxSizer* p_pcSection, const wxString& p_sName, bool p_bState);
public:
    SP_DLG_GraphProperties(SP_GUI_Mainframe* p_pcParent,
        SP_DS_Graph* p_pcGraph,
        const wxString& p_sTitle = wxT("Show attributes"),
        long p_nStyle = wxDEFAULT_DIALOG_STYLE);

    wxSizer* AddSection(const wxString& p_sName);
    bool AddFlagLine(wxSizer* p_pcSection, SP_DS_Attribute* p_pcAttr);

    /* EVENTS */
    /**	\brief	The OnDlgOk function

	    \param	p_cEvent	the event object as generated by wx'

	    This method is called, if the user clicks the 'OK' button
    */
    void OnDlgOk(wxCommandEvent& p_cEvent);
    /**	\brief	The OnDlgCancel function

	    \param	p_cEvent	the event object as generated by wx'

	    This method is called, if the user clicks the 'Cancel' button, pushes ESC
        or closes the dialog with the window-close methods of the ui-manager.
    */
    void OnDlgCancel(wxCommandEvent& p_cEvent);

private:
	wxCheckBox* m_pcDotShowBox;
	void ShowDotExpression();
	void SwitchDot();
	void SetEdgeShow( wxString p_sEdgeClass, bool p_bShowDot);
	



};

#endif // __SP_DLG_GRAPHPROPERTIES_H__

