//////////////////////////////////////////////////////////////////////
// $Source: $
// $Author: george assaf $
// $Version: 0.0 $
// $Revision: 1.30 $
// $Date: 2021/01/08 11:55:00 $
// Short Description: 
//////////////////////////////////////////////////////////////////////
#ifndef __SP_DLG_SAMPLING_PROPORTIES__
#define __SP_DLG_SAMPLING_PROPORTIES__

#include <wx/wx.h>
#include "FuzzyReasoning.h"
 
class SP_DLG_SamplingProperties : public wxDialog
{
private:
	DECLARE_EVENT_TABLE()
	//! the top level sizer
	wxBoxSizer* m_pcSizer;
	fuzzification::FuzzyReasoning* m_fr;


	std::vector<wxControl*> m_apcPropertiesCtrl;

	int  m_nSmplingAlgo;
	DECLARE_CLASS(SP_DLG_SamplingProperties)
protected:

	virtual void SetProperties();
	virtual void GetProperties();

public:
	SP_DLG_SamplingProperties(
		 wxWindow* p_pcParent, fuzzification::FuzzyReasoning* p_fr, const int& p_nSamplingAlgo = 0,
		const wxString& p_sTitle = wxT("Sampling Properties"),
		long p_nStyle = wxDEFAULT_DIALOG_STYLE);

	/* EVENTS */
	/**	\brief	The OnDlgOk function

	\param	p_cEvent	the event object as generated by wx'

	This method is called, if the user clicks the 'OK' button
	*/
	void OnDlgOk(wxCommandEvent& p_cEvent);
	/**	\brief	The OnDlgCancel function

	\param	p_cEvent	the event object as generated by wx'

	This method is called, if the user clicks the 'Cancel' button, pushes ESC
	or closes the dialog with the window-close methods of the ui-manager.
	*/
	void OnDlgCancel(wxCommandEvent& p_cEvent);
};

#endif // __SP_DLG_SAMPLING_PROPORTIES__


